- hosts: webserver
  remote_user: root
  become: yes
  become_user: root
  vars:
    http_port: 80
    NODEJS_VERSION: '8'
    ansible_distribution_release: 'xenial'
  tasks:
  - name: Delete the lock files
    file:
      state: absent
      path: /var/lib/dpkg/lock

  - name: Force package to reconfigure
    command: sudo dpkg --configure -a

  - name: Update apt packages
    apt:
      update_cache: yes

  # Mount volume under root
  - name: create a directory
    file: path=/node_web state=directory

  - name: format disk as ext4
    filesystem:
      fstype: ext4
      dev: /dev/vdc

  - name: mount volume
    mount: name=/node_web/ src=/dev/vdc fstype=ext4 state=mounted

  # Install useful packages
  - name: Install git
    command: sudo apt install git -y

  - name: Install apache2
    command: sudo apt-get install apache2 -y

  - name: Install the gpg key for nodejs LTS
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Install the nodejs
    apt:
      name: nodejs
      state: present

  # Download web code
  - name: Create a directory
    file: path=/node_web/web_code state=directory

  - name: Clone
    command: sudo git clone https://github.com/haorans1994/Cloud_Project2018.git
    args:
      chdir: /node_web/web_code/

  - name: Install yarn
    npm:
      name: yarn
      global: yes

  - name: Clean yarn cache
    command: yarn cache clean
    args:
      chdir: /node_web/web_code/Cloud_Project2018/

  - name: Remove node_modules
    command: sudo rm -rf node_modules
    args:
      chdir: /node_web/web_code/Cloud_Project2018/

  - name: Install all the dependencies of project
    command: sudo yarn install
    args:
      chdir: /node_web/web_code/Cloud_Project2018/web-app/

  - name: Build yarn
    command: sudo yarn build
    args:
      chdir: /node_web/web_code/Cloud_Project2018/web-app/

  # Move folder to apache server directory
  - name: Remove default html
    file:
      state: absent
      path: /var/www/html/
      
  - name: Move build directory to apache server
    command: sudo mv /node_web/web_code/Cloud_Project2018/web-app/build/ /var/www/html/